version: "3.2"

services:
#  almond:
#    image: joshuakwan/almond
#    networks:
#      - data-network
#    volumes:
#      - ./resources:/etc/almond
#    ports:
#      - "8080:8080"

  alertmanager:
    image: prom/alertmanager:v0.15.0-rc.1
    networks:
      - data-network
#    depends_on:
#      - almond
    restart: on-failure
    ports:
      - "9093:9093"
    volumes:
      - ./resources:/etc/almond:ro
    command:
      - --config.file=/etc/almond/alertmanager.yml

  prometheus:
    image: prom/prometheus
    networks:
      - data-network
#    depends_on:
#      - almond
    restart: on-failure
    ports:
      - "9090:9090"
    volumes:
      - ./resources:/etc/almond:ro
    command:
      - --config.file=/etc/almond/prometheus.yml

  grafana:
    image: grafana/grafana
    networks:
      - data-network
    ports:
      - "3000:3000"

  # consul cluster
  consul-agent-1: &consul-agent
    image: consul:latest
    networks:
      - consul-network
    command: "agent -retry-join consul-server-bootstrap -client 0.0.0.0"

  consul-agent-2:
    <<: *consul-agent

  consul-agent-3:
    <<: *consul-agent

  consul-server-1: &consul-server
    <<: *consul-agent
    command: "agent -server -retry-join consul-server-bootstrap -client 0.0.0.0"

  consul-server-2:
    <<: *consul-server

  consul-server-bootstrap:
    image: consul:latest
    ports:
      - "8300:8300"
      - "8400:8400"
      - "8500:8500"
      - "8600:8600"
    networks:
      consul-network:
        ipv4_address: 172.20.0.253
      data-network:
    command: "agent -server -bootstrap-expect 3 -ui -client 0.0.0.0 -bind 172.20.0.253 "

networks:
  data-network:
    ipam:
      driver: default
      config:
        - subnet: 172.19.0.0/16
  consul-network:
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/16
