version: "3.2"

services:
  almond:
    image: joshuakwan/almond
    volumes:
      - ./resources:/etc/almond
    ports:
      - "8080:8080"

  alertmanager:
    image: prom/alertmanager
    depends_on:
      - almond
    restart: on-failure
    ports:
      - "9093:9093"
    volumes:
      - ./resources:/etc/almond:ro
    command:
      - --config.file=/etc/almond/alertmanager.yml

  prometheus:
    image: prom/prometheus
    depends_on:
      - almond
    restart: on-failure
    ports:
      - "9090:9090"
    volumes:
      - ./resources:/etc/almond:ro
    command:
      - --config.file=/etc/almond/prometheus.yml

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"

  # consul cluster
  consul-agent-1: &consul-agent
    image: consul:latest
    networks:
      - consul-demo
    command: "agent -retry-join consul-server-bootstrap -client 0.0.0.0"

  consul-agent-2:
    <<: *consul-agent

  consul-agent-3:
    <<: *consul-agent

  consul-server-1: &consul-server
    <<: *consul-agent
    command: "agent -server -retry-join consul-server-bootstrap -client 0.0.0.0"

  consul-server-2:
    <<: *consul-server

  consul-server-bootstrap:
    <<: *consul-agent
    ports:
      - "8400:8400"
      - "8500:8500"
      - "8600:8600"
    command: "agent -server -bootstrap-expect 3 -ui -client 0.0.0.0"