global:
  resolve_timeout: 5m
  http_config: {}
  smtp_from: alertmanager@example.org
  smtp_hello: localhost
  smtp_smarthost: localhost:25
  smtp_auth_username: alertmanager
  smtp_auth_password: <secret>
  smtp_require_tls: true
  pagerduty_url: https://events.pagerduty.com/v2/enqueue
  hipchat_api_url: https://api.hipchat.com/
  hipchat_auth_token: <secret>
  opsgenie_api_url: https://api.opsgenie.com/
  wechat_api_url: https://qyapi.weixin.qq.com/cgi-bin/
  victorops_api_url: https://alert.victorops.com/integrations/generic/20131114/alert/
route:
  receiver: team-X-mails
  group_by:
  - alertname
  - cluster
  - service
  routes:
  - receiver: team-X-mails
    match_re:
      service: ^(?:^(?:^(?:^(?:^(?:^(foo1|foo2|baz)$)$)$)$)$)$
    routes:
    - receiver: team-X-pager
      match:
        severity: critical
  - receiver: team-Y-mails
    match:
      service: files
    routes:
    - receiver: team-Y-pager
      match:
        severity: critical
  - receiver: team-DB-pager
    group_by:
    - alertname
    - cluster
    - database
    match:
      service: database
    routes:
    - receiver: team-X-pager
      match:
        owner: team-X
    - receiver: team-Y-pager
      match:
        owner: team-Y
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 4h
inhibit_rules:
- source_match:
    severity: critical
  target_match:
    severity: warning
  equal:
  - alertname
  - cluster
  - service
receivers:
- name: team-X-mails
  email_configs:
  - send_resolved: false
    to: team-X+alerts@example.org
    from: alertmanager@example.org
    hello: localhost
    smarthost: localhost:25
    auth_username: alertmanager
    auth_password: <secret>
    html: '{{ template "email.default.html" . }}'
    require_tls: true
- name: team-X-pager
  email_configs:
  - send_resolved: false
    to: team-X+alerts-critical@example.org
    from: alertmanager@example.org
    hello: localhost
    smarthost: localhost:25
    auth_username: alertmanager
    auth_password: <secret>
    html: '{{ template "email.default.html" . }}'
    require_tls: true
  pagerduty_configs:
  - send_resolved: true
    http_config: {}
    service_key: <secret>
    url: https://events.pagerduty.com/v2/enqueue
    client: '{{ template "pagerduty.default.client" . }}'
    client_url: '{{ template "pagerduty.default.clientURL" . }}'
    description: '{{ template "pagerduty.default.description" .}}'
    details:
      firing: '{{ template "pagerduty.default.instances" .Alerts.Firing }}'
      num_firing: '{{ .Alerts.Firing | len }}'
      num_resolved: '{{ .Alerts.Resolved | len }}'
      resolved: '{{ template "pagerduty.default.instances" .Alerts.Resolved }}'
- name: team-Y-mails
  email_configs:
  - send_resolved: false
    to: team-Y+alerts@example.org
    from: alertmanager@example.org
    hello: localhost
    smarthost: localhost:25
    auth_username: alertmanager
    auth_password: <secret>
    html: '{{ template "email.default.html" . }}'
    require_tls: true
- name: team-Y-pager
  pagerduty_configs:
  - send_resolved: true
    http_config: {}
    service_key: <secret>
    url: https://events.pagerduty.com/v2/enqueue
    client: '{{ template "pagerduty.default.client" . }}'
    client_url: '{{ template "pagerduty.default.clientURL" . }}'
    description: '{{ template "pagerduty.default.description" .}}'
    details:
      firing: '{{ template "pagerduty.default.instances" .Alerts.Firing }}'
      num_firing: '{{ .Alerts.Firing | len }}'
      num_resolved: '{{ .Alerts.Resolved | len }}'
      resolved: '{{ template "pagerduty.default.instances" .Alerts.Resolved }}'
- name: team-DB-pager
  pagerduty_configs:
  - send_resolved: true
    http_config: {}
    service_key: <secret>
    url: https://events.pagerduty.com/v2/enqueue
    client: '{{ template "pagerduty.default.client" . }}'
    client_url: '{{ template "pagerduty.default.clientURL" . }}'
    description: '{{ template "pagerduty.default.description" .}}'
    details:
      firing: '{{ template "pagerduty.default.instances" .Alerts.Firing }}'
      num_firing: '{{ .Alerts.Firing | len }}'
      num_resolved: '{{ .Alerts.Resolved | len }}'
      resolved: '{{ template "pagerduty.default.instances" .Alerts.Resolved }}'
- name: team-X-hipchat
  hipchat_configs:
  - send_resolved: false
    http_config: {}
    api_url: https://api.hipchat.com/
    auth_token: <secret>
    room_id: "85"
    from: '{{ template "hipchat.default.from" . }}'
    notify: true
    message: '{{ template "hipchat.default.message" . }}'
    message_format: html
    color: '{{ if eq .Status "firing" }}red{{ else }}green{{ end }}'
- name: team-C17
  email_configs:
  - send_resolved: true
    to: c17_alerts@example.org
    from: alertmanager@example.org
    hello: localhost
    smarthost: localhost:25
    auth_username: alertmanager
    auth_password: <secret>
    html: '{{ template "email.default.html" . }}'
    require_tls: true
- name: team-C18
  email_configs:
  - send_resolved: true
    to: c18_alerts@example.org
    from: alertmanager@example.org
    hello: localhost
    smarthost: localhost:25
    auth_username: alertmanager
    auth_password: <secret>
    html: '{{ template "email.default.html" . }}'
    require_tls: true
- name: team-C19
  email_configs:
  - send_resolved: true
    to: c19_alerts@example.org
templates: []
