global:
  resolve_timeout: 5m
  smtp_from: alertmanager@example.org
  smtp_smarthost: localhost:25
  smtp_auth_username: alertmanager
  smtp_auth_password: password
  smtp_require_tls: true
  victorops_api_url: https://alert.victorops.com/integrations/generic/20131114/alert/
  pagerduty_url: https://events.pagerduty.com/v2/enqueue
  opsgenie_api_url: https://api.opsgenie.com/
  hipchat_api_url: https://api.hipchat.com/
  hipchat_auth_token: "1234556789"
templates: []
route:
  receiver: team-X-mails
  group_by:
  - alertname
  - cluster
  - service
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 4h
  routes:
  - receiver: team-X-mails
    match_re:
      service: ^(?:^(foo1|foo2|baz)$)$
    routes:
    - receiver: team-X-pager
      match:
        severity: critical
  - receiver: team-Y-mails
    match:
      service: files
    routes:
    - receiver: team-Y-pager
      match:
        severity: critical
  - receiver: team-DB-pager
    group_by:
    - alertname
    - cluster
    - database
    match:
      service: database
    routes:
    - receiver: team-X-pager
      match:
        owner: team-X
    - receiver: team-Y-pager
      match:
        owner: team-Y
receivers:
- name: team-X-mails
  email_configs:
  - send_resolved: false
    to: team-X+alerts@example.org
- name: team-X-pager
  email_configs:
  - send_resolved: false
    to: team-X+alerts-critical@example.org
  pagerduty_configs:
  - service_key: <team-X-key>
- name: team-Y-mails
  email_configs:
  - send_resolved: false
    to: team-Y+alerts@example.org
- name: team-Y-pager
  pagerduty_configs:
  - service_key: <team-Y-key>
- name: team-DB-pager
  pagerduty_configs:
  - service_key: <team-DB-key>
- name: team-X-hipchat
  hipchat_configs:
  - send_resolved: false
    room_id: "85"
    auth_token: <auth_token>
    notify: true
    message_format: html
inhibit_rules:
- target_match:
    severity: warning
  source_match:
    severity: critical
  equal:
  - alertname
  - cluster
  - service
