global:
  scrape_interval: 15s
  evaluation_interval: 15s
rule_files:
- rules/default.rules
scrape_configs:
- job_name: prometheus
  static_configs:
  - targets:
    - prometheus:9090
- job_name: consul
  consul_sd_configs:
  - server: consul-server-bootstrap:8500
    scheme: http
    tag_separator: ','
- job_name: spiderman
  consul_sd_configs:
  - server: localhost:8500
    services:
    - spiderman
- job_name: xman
  consul_sd_configs:
  - server: http://192.168.99.100:8500
    services:
    - xman
alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - alertmanager:9093
